//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetStatusInfo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class AllSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AllSettings defaultInstance = ((AllSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AllSettings())));
        
        public static AllSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//query excluding select ending with locationFieldName=\'")]
        public string stockQueryRoot {
            get {
                return ((string)(this["stockQueryRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//query ending with locationFieldName=\'")]
        public string nonStockQuery {
            get {
                return ((string)(this["nonStockQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//query ending with locationFieldName=\'=\'")]
        public string phoneQuery {
            get {
                return ((string)(this["phoneQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//query returning 1 column")]
        public string locationQuery {
            get {
                return ((string)(this["locationQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//SqlConnection connectionName = new SqlConnection(connectionString);")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//| separated list of locations ")]
        public string GetsStockItems {
            get {
                return ((string)(this["GetsStockItems"]));
            }
            set {
                this["GetsStockItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//| separated list of locations that can\'t be delivered to, for example \"All Site" +
            "s\"")]
        public string CantBeDeliveredTo {
            get {
                return ((string)(this["CantBeDeliveredTo"]));
            }
            set {
                this["CantBeDeliveredTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//| separated list of db columns which can\'t be searched by the user")]
        public string NonSearchableFields {
            get {
                return ((string)(this["NonSearchableFields"]));
            }
            set {
                this["NonSearchableFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//| separated list of comma-separated pairs where the db column name is first and" +
            " the display name is 2nd")]
        public string ColumnFriendlyNameMapping {
            get {
                return ((string)(this["ColumnFriendlyNameMapping"]));
            }
            set {
                this["ColumnFriendlyNameMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//db field name which matches the count of the item in the warehouse")]
        public string AmountFieldName {
            get {
                return ((string)(this["AmountFieldName"]));
            }
            set {
                this["AmountFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//if 1 ship-to location has sublocations, they can be placed here as a | separate" +
            "d list")]
        public string CompoundLocationList {
            get {
                return ((string)(this["CompoundLocationList"]));
            }
            set {
                this["CompoundLocationList"] = value;
            }
        }
    }
}
